# Generated by Django 4.2.4 on 2023-12-03 20:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_is_admin_userprofile_is_sruff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='login',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
