# Generated by Django 4.2.4 on 2023-12-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_is_sruff_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
