# Generated by Django 4.2.4 on 2023-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrequest',
            name='operand1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationrequest',
            name='operand2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationrequest',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
