# Generated by Django 4.2.4 on 2024-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_operationrequest_operand1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
